# name: CI/CD Pipeline

# permissions:
#   contents: write

# on:
#   push:
#     branches: [ dev ]
#   pull_request:
#     branches: [ dev ]

# jobs:
#   shellcheck:
#     name: Shellcheck
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       - name: Run ShellCheck
#         uses: ludeeus/action-shellcheck@master

#   build-and-scan:
#     runs-on: ubuntu-latest
#     services:
#       docker:
#         image: docker:20.10.7-dind

#     steps:
#       - uses: actions/checkout@v4
#         with:
#           fetch-depth: 0

#       - name: Get lowercase repo
#         id: repo
#         run: echo "repo=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

#       - name: Get backend SHA
#         id: backend_sha
#         run: echo "backend_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

#       - name: Build backend Docker image
#         if: steps.backend-changed.outputs.changed == 'true'
#         run: |
#           docker build -t ghcr.io/${{ steps.repo.outputs.repo }}/backend:${{ steps.backend_sha.outputs.backend_sha }} ./apps/backend

#       - name: Log in to GHCR
#         run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

#       - name: Push backend Docker image
#         if: steps.backend-changed.outputs.changed == 'true'
#         run: |
#           docker push ghcr.io/${{ steps.repo.outputs.repo }}/backend:${{ steps.backend_sha.outputs.backend_sha }}

#       - name: Make backend package public
#         if: steps.backend-changed.outputs.changed == 'true'
#         run: |
#           curl -X PATCH \
#             -H "Accept: application/vnd.github+json" \
#             -H "Authorization: Bearer ${{ secrets.GHCR_PAT }}" \
#             -H "X-GitHub-Api-Version: 2022-11-28" \
#             https://api.github.com/user/packages/container/devops-ci-cd-k8s-pipeline-demo%2Fbackend \
#             -d '{"visibility":"public"}'

#       - name: Install yq
#         run: |
#           sudo wget https://github.com/mikefarah/yq/releases/download/v4.40.5/yq_linux_amd64 -O /usr/bin/yq
#           sudo chmod +x /usr/bin/yq

#       - name: Update backend image tag in Helm values
#         if: steps.backend-changed.outputs.changed == 'true'
#         run: |
#           yq e '.backend.tag = "${{ steps.backend_sha.outputs.backend_sha }}"' -i charts/myapp/values-dev.yaml

#       - name: Show tag lines (debug)
#         run: |
#           grep 'tag:' charts/myapp/values-dev.yaml
#           grep 'tag:' charts/myapp/values-prod.yaml

#       - name: Auto-commit tag update to dev
#         if: github.ref == 'refs/heads/dev' && (steps.backend-changed.outputs.changed == 'true' || steps.frontend-changed.outputs.changed == 'true')
#         run: |
#           git config user.name "github-actions"
#           git config user.email "github-actions@users.noreply.github.com"
#           git add .
#           git commit -m "CI: Update image tags to backend:${{ steps.backend_sha.outputs.backend_sha }} || echo "No changes"
#           git push origin dev

#       - name: Create Pull Request for tag update to helm-update
#         if: github.ref == 'refs/heads/' && (steps.backend-changed.outputs.changed == 'true' || steps.frontend-changed.outputs.changed == 'true')
#         uses: peter-evans/create-pull-request@v5
#         with:
#           token: ${{ secrets.GHCR_PAT }}
#           commit-message: "CI: Update image tags to backend:${{ steps.backend_sha.outputs.backend_sha }} frontend:${{ steps.frontend_sha.outputs.frontend_sha }}"
#           title: "CI: Update image tags to backend:${{ steps.backend_sha.outputs.backend_sha }} frontend:${{ steps.frontend_sha.outputs.frontend_sha }}"
#           body: "Automated PR to update image tags in Helm values files."
#           branch: "ci/tag-update"
#           add-paths: |
#             charts/myapp/values-dev.yaml
#             charts/myapp/values-prod.yaml