name: Helm Deploy to External Cluster
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Print current working directory
        run: pwd
      - name: List files in current directory
        run: ls -la
      
      - name: Copy files to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          port: 22
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "myapp/"
          target: "/home/ubuntu/Accuknox-DevOps-trainee/myapp"
          overwrite: true
      
      - name: Deploy with Helm
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          timeout: 15s  
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            pwd
            ls -la
            cd /home/ubuntu/Accuknox-DevOps-trainee/myapp
            if helm upgrade --install myapp . -f values.yaml --wait --timeout=10m; then
              echo "✅ Deployment successful"
              helm status myapp
              kubectl get pods -l app.kubernetes.io/name=myapp
            else
              echo "❌ Deployment failed"
              helm status myapp
              exit 1
            fi
